// Explicit reviewed export columns. New schema columns are private by default.
pub(super) const TABLES: &[(&str, &str)] = &[
    (
        "ai_call_reservations",
        "id,public_id,workspace_id,actor_id,operation,control_generation,status,created_at,finished_at",
    ),
    (
        "artifact_destination_settings",
        "id,workspace_id,project_id,artifact_type,provider,target_id,label,enabled,revision,updated_by_actor_id,updated_at",
    ),
    (
        "artifact_document_versions",
        "id,public_id,document_id,workspace_id,project_id,version,title,body_markdown,structured_content,status,created_by_actor_id,created_at,validated_at,content_hash",
    ),
    (
        "artifact_documents",
        "id,public_id,workspace_id,project_id,artifact_type,current_version_id,created_by_actor_id,created_at,updated_at",
    ),
    (
        "artifact_version_sources",
        "id,workspace_id,version_id,source_project_id,source_kind,knowledge_version_id,context_pack_id,deliverable_id,session_id,source_artifact_version_id,source_public_id,snapshot",
    ),
    (
        "artifacts",
        "id,public_id,workspace_id,project_id,execution_id,deliverable_id,external_reference_id,artifact_type,title,reference,metadata,created_at",
    ),
    (
        "audit_events",
        "id,public_id,workspace_id,project_id,actor_id,action,object_kind,object_public_id,before_state,after_state,occurred_at",
    ),
    (
        "context_nodes",
        "id,public_id,workspace_id,project_id,parent_id,agent_profile_id,node_key,title,description,summary,context_rules,preferred_entry_types,preferred_deliverable_types,created_at,updated_at",
    ),
    (
        "context_pack_scope_sources",
        "id,workspace_id,project_id,context_pack_id,source_project_id,source_kind,source_public_id,knowledge_version_id,artifact_version_id,decision,reason_code,explanation,rank,estimated_tokens,is_mandatory",
    ),
    (
        "context_pack_scope_versions",
        "id,workspace_id,project_id,context_pack_id,source_project_id,graph_version",
    ),
    (
        "context_pack_selection_items",
        "id,public_id,workspace_id,project_id,context_pack_id,candidate_kind,candidate_public_id,knowledge_entry_version_id,external_reference_observation_id,decision,reason_code,explanation,rank,estimated_tokens,is_mandatory,created_at",
    ),
    (
        "context_pack_sources",
        "id,workspace_id,project_id,context_pack_id,knowledge_entry_id,knowledge_entry_version_id,source_role,included_reason",
    ),
    (
        "context_packs",
        "id,public_id,workspace_id,project_id,source_node_id,target_node_id,target_agent_profile_id,task_kind,objective,content,version,status,source_graph_version,compiler_version,selection_mode,content_hash,token_budget,estimated_tokens,supersedes_context_pack_id,stale_reason,compiled_at,invalidated_at",
    ),
    (
        "deliverable_sections",
        "id,public_id,workspace_id,project_id,deliverable_id,section_key,title,body,ordinal,source_data",
    ),
    (
        "deliverable_sources",
        "id,public_id,workspace_id,project_id,deliverable_id,source_kind,source_public_id,knowledge_entry_version_id,context_pack_id,external_reference_observation_id,model_run_id,source_role,included_reason,created_at",
    ),
    (
        "deliverables",
        "id,public_id,workspace_id,project_id,context_node_id,contract_id,source_session_id,source_context_pack_id,lineage_public_id,supersedes_deliverable_id,source_graph_version,content_hash,deliverable_type,title,summary,content,status,coverage_status,version,committed_at,stale_at,created_at,updated_at",
    ),
    (
        "domain_events",
        "requested_by_actor_id,id,public_id,workspace_id,project_id,event_type,aggregate_kind,aggregate_public_id,payload,status,attempt_count,available_at,last_error_code,last_error_message,occurred_at,processed_at,failed_at",
    ),
    (
        "edges",
        "id,public_id,workspace_id,project_id,source_kind,source_public_id,target_kind,target_public_id,edge_type,status,provenance,created_by_actor_id,created_at,target_project_id",
    ),
    (
        "evidences",
        "id,public_id,workspace_id,project_id,requirement_entry_id,requirement_version_id,deliverable_id,deliverable_section_id,artifact_id,external_reference_id,evidence_type,title,description,source_reference,status,created_at",
    ),
    (
        "execution_events",
        "id,public_id,workspace_id,project_id,execution_id,event_type,sequence_number,payload,created_at",
    ),
    (
        "executions",
        "id,public_id,workspace_id,project_id,task_id,executor_key,status,result,started_at,completed_at,created_at",
    ),
    (
        "external_reference_observations",
        "id,public_id,workspace_id,project_id,external_reference_id,observation_status,content_hash,etag,observed_state,provider_updated_at,observed_at",
    ),
    (
        "external_references",
        "id,public_id,workspace_id,project_id,tool_connection_id,provider,object_kind,external_id,canonical_url,repository_full_name,display_title,sync_status,etag,last_synced_at,last_error_code,last_error_message,created_by_actor_id,created_at,updated_at",
    ),
    (
        "gates",
        "id,public_id,workspace_id,project_id,context_node_id,gate_key,status,evaluation,graph_version,evaluated_at",
    ),
    (
        "handoffs",
        "id,public_id,workspace_id,project_id,source_session_id,target_session_id,context_pack_id,status,initiated_by_actor_id,created_at,completed_at",
    ),
    (
        "github_code_corpora",
        "id,public_id,workspace_id,project_id,repository,commit_sha,commit_verified,requested_paths,requested_by_actor_id,observed_at",
    ),
    (
        "github_code_file_observations",
        "id,public_id,workspace_id,project_id,corpus_id,path,status,reason_code,blob_sha,content_hash,content_text,line_count,observed_at",
    ),
    (
        "insight_resolutions",
        "id,public_id,workspace_id,project_id,insight_id,action,knowledge_entry_version_id,source_graph_version,resulting_graph_version,justification,resolved_by_actor_id,created_at",
    ),
    (
        "insight_sources",
        "id,workspace_id,project_id,insight_id,source_role,object_kind,object_public_id,knowledge_entry_version_id",
    ),
    (
        "insights",
        "id,public_id,workspace_id,project_id,steward_assessment_id,insight_type,status,severity,confidence,title,explanation,resolution_justification,resolved_by_actor_id,resolved_at,detected_at,updated_at",
    ),
    (
        "knowledge_entries",
        "id,public_id,workspace_id,project_id,context_node_id,entry_type,status,latest_version,created_at,updated_at",
    ),
    (
        "knowledge_entry_versions",
        "id,public_id,knowledge_entry_id,workspace_id,project_id,context_node_id,version_number,entry_type,title,statement,rationale,status,author_actor_id,origin_type,origin_public_id,source_message_public_id,created_at",
    ),
    (
        "messages",
        "id,public_id,workspace_id,project_id,session_id,client_message_id,role,content,agent_scope,metadata,created_at,author_actor_id",
    ),
    (
        "model_runs",
        "id,public_id,workspace_id,project_id,session_id,context_pack_id,started_by_actor_id,operation,provider,model,prompt_version,schema_version,source_graph_version,input_hash,source_public_ids,provider_response_id,status,output,usage,input_tokens,output_tokens,estimated_cost,latency_ms,attempt_count,error_class,error_message,started_at,completed_at,created_at,updated_at",
    ),
    (
        "mutation_proposals",
        "id,public_id,workspace_id,project_id,session_id,source_message_id,proposed_by_agent_profile_id,entry_type,title,statement,rationale,status,source_data,decided_by_actor_id,decided_at,created_at",
    ),
    (
        "projects",
        "id,public_id,workspace_id,template_id,name,objective,summary,status,graph_version,created_by_actor_id,created_at,updated_at,scope_kind",
    ),
    (
        "publication_jobs",
        "id,public_id,workspace_id,project_id,artifact_version_id,source_ticket_index,connection_id,connection_revision,requested_by_actor_id,provider,target_id,title,body_markdown,content_hash,status,attempt_count,external_id,external_url,error_code,created_at,updated_at",
    ),
    (
        "publication_observations",
        "id,public_id,workspace_id,publication_job_id,observed_at,observation_kind,external_id,external_url,remote_updated_at,snapshot",
    ),
    (
        "requirement_coverage",
        "id,workspace_id,project_id,requirement_entry_id,requirement_version_id,deliverable_id,deliverable_section_id,evidence_id,status,explanation,updated_at",
    ),
    (
        "sessions",
        "id,public_id,workspace_id,project_id,context_node_id,agent_profile_id,context_pack_id,title,status,created_by_actor_id,created_at,updated_at",
    ),
    (
        "steward_assessment_sources",
        "id,workspace_id,project_id,assessment_id,source_role,knowledge_entry_version_id",
    ),
    (
        "steward_assessments",
        "id,public_id,workspace_id,project_id,model_run_id,graph_version,fingerprint,classification,severity,confidence,title,explanation,created_at",
    ),
    (
        "steward_scan_progress",
        "id,workspace_id,status,last_error_code,updated_at",
    ),
    (
        "steward_scan_sources",
        "id,workspace_id,project_id,source_public_id,source_kind,examined_pairs,omitted_neighbors,completed_at",
    ),
    (
        "steward_scope_sources",
        "id,workspace_id,project_id,assessment_id,source_project_id,source_role,source_kind,source_public_id,knowledge_version_id,artifact_version_id,external_observation_id,publication_observation_id,github_code_file_observation_id,source_snapshot",
    ),
    (
        "tasks",
        "id,public_id,workspace_id,project_id,context_pack_id,contract_id,title,status,created_at,updated_at",
    ),
    (
        "workspace_members",
        "id,public_id,workspace_id,actor_id,role,invitation_status,invited_by_actor_id,accepted_at,created_at,updated_at",
    ),
    (
        "workspace_automation_controls",
        "id,workspace_id,enabled,generation,updated_by_actor_id,updated_at",
    ),
    (
        "workspaces",
        "id,public_id,owner_actor_id,name,created_at,updated_at,description",
    ),
];
